### ISSUE TITLE
can't use the playbook anymore, error on finding the security requirement

### ISSUE THREAD

**Issue by lucamaf** [nmasse-itix/threescale-cicd#33]
here is the error:

```
TASK [nmasse-itix.threescale-cicd : Find the security requirement to use] ********************************************************************************************************************
fatal: [acme-admin.apps.openshift.es]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: dict_keys object has no element 0\n\nThe error appears to have been in '/home/remote/luferrar/.ansible/roles/nmasse-itix.threescale-cicd/tasks/read_openapi_file.yml': line 118, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Find the security requirement to use\n  ^ here\n"}


```
attached the swagger file
[echo-swagger.yaml.txt](https://github.com/nmasse-itix/threescale-cicd/files/2703595/echo-swagger.yaml.txt)

**Comment by nmasse-itix** [comment]
Hi @lucamaf,

Thanks for reporting this ! I investigated and it appears the new version of Ansible made the switch from Python 2 to Python 3 with some breaking changes. 

If you downgrade to a previous version of Ansible or one on Python 2, it works. 

I will investigate for a definitive fix. 👍

**Comment by nmasse-itix** [comment]
I @lucamaf,

I found the culprit: at some point of the playbook I need to fetch the first item of a dictionary. 

I used the following syntax:
```python
my_dict.keys()[0]
```

This syntax is not valid anymore with Python 3. 

The correct Python3/Jinja2 syntax is:

```python
my_dict.keys()|list|first
```

**Comment by nmasse-itix** [comment]
Fixed by #34.

**Comment by s3n29t** [comment]
When is a next release planned for Ansible Galaxy?

**Comment by nmasse-itix** [comment]
Hi @s3n29t 

The master branch will be the next release and that would be a 1.0 version since the Ansible role interface has breaking changes with the previous 0.0.x versions. 

I have to test the playbook on different scenarios (on-premises, saas, different gateway configuration, etc.) and then I will release a new version on the Ansible Galaxy. 

Maybe between mid and end of January ?

**Comment by wired00** [comment]
what about if you wanted to get the second key?

**Comment by nmasse-itix** [comment]
@wired00  Like this ?
```python
(my_dict.keys()|list)[1]
```
